// libraries/helper/botdetect/examples/simple-api/simple-api-angular-captcha-example/angular-src/app/basic/basic.component.ts
import { Component, ViewChild } from '@angular/core';
import { Observable } from 'rxjs/Rx';

import { CaptchaComponent } from 'angular-captcha';

import { BasicService } from './basic.service';

@Component({
  moduleId: module.id,
  selector: 'basic-form',
  templateUrl: 'basic.component.html',
  styleUrls: ['basic.component.css'],
  providers: [BasicService]
})
export class BasicComponent {

  /**
   * Captcha validation messages.
   */
  errorMessages: string;
  successMessages: string;

  /**
   * BotDetect CAPTCHA component.
   */
  @ViewChild(CaptchaComponent) captchaComponent: CaptchaComponent;

  constructor(private basicService: BasicService) { }

  /**
   * Validate captcha at server-side.
   */
  validate(value, valid): void {
    // use validateUnsafe() method to perform client-side captcha validation
    this.captchaComponent.validateUnsafe((isCaptchaCodeCorrect: boolean) => {

      if (isCaptchaCodeCorrect) {

        // after UI form validation passed, 
        // we will need to validate captcha at server-side once before we save form data in database, etc.

        const postData = {
          captchaCode: this.captchaComponent.captchaCode,
          captchaId: this.captchaComponent.captchaId
        };
      
        this.basicService.send(postData)
          .subscribe(
            response => {
              if (response.success) {
                // captcha, other form data passed and the data is also stored in database
                this.successMessages = 'Your message was sent successfully!';
                this.errorMessages = '';
              } else {
                // captcha validation failed at server-side
                this.errorMessages = 'CAPTCHA validation falied.';
                this.successMessages = '';
              }

              // always reload captcha image after validating captcha at server-side 
              // in order to update new captcha code for current captcha id
              this.captchaComponent.reloadImage();
            },
            error => {
              throw new Error(error);
            });
      } else {
        this.errorMessages = 'CAPTCHA validation falied.';
        this.successMessages = '';
      }
    });
  }

}

<form novalidate #f="ngForm" (ngSubmit)="validate(f.value, f.valid)">

  <div class="alert alert-success" *ngIf="successMessages">
    {{ successMessages }}
  </div>

  <div class="alert alert-error" *ngIf="errorMessages">
    {{ errorMessages }}
  </div>

  <!-- show captcha html -->
  <botdetect-captcha styleName="angularBasicCaptcha"></botdetect-captcha>  

  <label>
    <span>Retype the characters from the picture:</span>
    <input
      type="text"
      id="captchaCode"
      name="captchaCode"
      ngModel
      #captchaCode="ngModel"
      >
  </label>

  <button type="submit">Validate</button>
</form>

// libraries/helper/botdetect/examples/simple-api/simple-api-react-captcha-example/react-src/src/views/basic.jsx
import React from 'react';
import axios from 'axios';
import { Captcha } from 'reactjs-captcha';

class Basic extends React.Component {

    constructor(props) {
        super(props);
    }

    componentDidMount() {
        // UI captcha validation on blur event by using the custom 'validatecaptcha' event
        // and checking the 'event.detail' variable to either show error messages
        // or check captcha code input field status when form is submitted
        document.getElementById('captchaCode').addEventListener('validatecaptcha', function (event) {
            // display or remove error message
            let isCaptchaCodeCorrect = event.detail;

            if (isCaptchaCodeCorrect) {
                document.getElementsByClassName('captcha-code-error')[0].innerHTML = '';
            } else {
                document.getElementsByClassName('captcha-code-error')[0].innerHTML = 'Incorrect code';
            }
        })
    }

    basicFormSubmit(event) {
      
        // captcha id for validating captcha at server-side
        let captchaId = this.captcha.getCaptchaId();

        // captcha code input value for validating captcha at server-side
        let captchaCode = this.captcha.getCaptchaCode();

        let postData = {
            captchaId: captchaId,
            captchaCode: captchaCode
        };

        let self = this;
        let formMessage = document.getElementById('form-messages');

        axios.post('form/basic.php', postData)
                .then(response => {
                    if (response.data.success) {
                        // captcha validation passed at server-side
                        formMessage.setAttribute('class', 'alert alert-success');
                        formMessage.innerHTML = 'CAPTCHA validation passed.';
                    } else {
                        // captcha validation failed at server-side
                        formMessage.setAttribute('class', 'alert alert-error');
                        formMessage.innerHTML = 'CAPTCHA validation falied.';
                    }
                    self.captcha.reloadImage();
                }).catch(function (error) {
                    throw new Error(error);
                });

        event.preventDefault();
    }

    render() {
        return (
            <section id="main-content">
                <form id="basicForm" method="POST" onSubmit={this.basicFormSubmit.bind(this)}>
                    <div id="form-messages"></div>

                    <Captcha styleName="reactBasicCaptcha" ref={(captcha) => {this.captcha = captcha}} />

                    <label>
                        <span>Retype the characters from the picture:</span>
                        <input type="text" name="captchaCode" id="captchaCode" data-correct-captcha />
                    </label>

                    <div className="error captcha-code-error"></div>

                    <button type="submit" id="submitButton">Validate</button>
                </form>
            </section>
        )
    }
}

export default Basic;
